apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despachos
  namespace: sistema-despachos
  labels:
    app: backend-despachos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-despachos
  template:
    metadata:
      labels:
        app: backend-despachos
    spec:
      containers:
        - name: backend-despachos
          # El pipeline deploy-backend-despachos.yml sobreescribe este tag con ${{ github.sha }}
          image: 218020533514.dkr.ecr.us-east-1.amazonaws.com/sistema-despachos-despachos:latest
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: db-credentials-despachos
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
